### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by antonyjsmith** [fifthsegment/Wpress-Extractor#12]
Getting this every time I try to run, I'm on Mac OS High Sierra.

```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x1e15a]

runtime stack:
runtime.throw(0x13e800, 0x2a)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.(*gcWork).dispose(0xc82001b220)
	/usr/local/go/src/runtime/mgcwork.go:164 +0x2a
runtime.gc.func2.1(0xc82001a000)
	/usr/local/go/src/runtime/mgc.go:1032 +0x30
runtime.handoffp(0xc82001a000)
	/usr/local/go/src/runtime/proc1.go:1229 +0x1bc
runtime.forEachP(0x14c5f8)
	/usr/local/go/src/runtime/proc1.go:786 +0x2fb
runtime.gc.func2()
	/usr/local/go/src/runtime/mgc.go:1033 +0x54
runtime.systemstack(0xc820484c40)
	/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc1.go:668

goroutine 5 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc82002bc98 sp=0xc82002bc90
runtime.gc(0x0)
	/usr/local/go/src/runtime/mgc.go:1034 +0x234 fp=0xc82002bf90 sp=0xc82002bc98
runtime.backgroundgc()
	/usr/local/go/src/runtime/mgc.go:897 +0x3d fp=0xc82002bfc0 sp=0xc82002bf90
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc82002bfc8 sp=0xc82002bfc0
created by runtime.startGC
	/usr/local/go/src/runtime/mgc.go:870 +0x186

goroutine 1 [syscall]:
syscall.Syscall(0x4, 0x4, 0xc820495400, 0x200, 0x200, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.write(0x4, 0xc820495400, 0x200, 0x200, 0x3, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_darwin_amd64.go:1360 +0x5f
syscall.Write(0x4, 0xc820495400, 0x200, 0x200, 0xc820495400, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:176 +0x4d
os.(*File).write(0xc82002e038, 0xc820495400, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:232 +0xd0
os.(*File).Write(0xc82002e038, 0xc820495400, 0x200, 0x200, 0x200, 0x0, 0x0)
	/usr/local/go/src/os/file.go:139 +0x8a
github.com/yani-/wpress.Reader.Extract(0x7ffeefbffbfb, 0x27, 0xc82002e028, 0x1, 0x0, 0x0, 0x0)
	/Users/abdullahirfan/go/src/github.com/yani-/wpress/reader.go:136 +0x8d3
main.main()
	/Users/abdullahirfan/godev/wpress_extractor.go:16 +0x193
```

**Comment by thiagoghisi** [comment]
Same problem here. I think we just have to regenerate the binaries from the go code on mac again. I'm trying to do that now to see if it solves the problem on Mac OS High Sierra...

**Comment by robrecord** [comment]
I have the same issue. I would very much appreciate if you could do help with this, @thiagoghisi !

**Comment by lopugit** [comment]
got this issue to.. high sierra

**Comment by musastudios** [comment]
Following.. Same errors on macOS Mojave

**Comment by mmehrle** [comment]
Same error here.

**Comment by buskerone** [comment]
+1 any progress on this?

**Comment by ronaldtveen** [comment]
Big Sur here, same error.

As a workaround I got my `.wpress` extracted via [these steps](https://dev.to/ofhouse/how-to-unpack-wpress-archive-files-created-by-the-all-in-one-wp-migration-wordpress-plugin-k63):

1. Install NodeJS, if not already installed
2. Navigate to the directory with your `.wpress` file
3. `npx wpress-extract yourfile.wpress`
4. Confirm the question asked

**Comment by gillesgoetsch** [comment]
> Big Sur here, same error.
> 
> As a workaround I got my `.wpress` extracted via [these steps](https://dev.to/ofhouse/how-to-unpack-wpress-archive-files-created-by-the-all-in-one-wp-migration-wordpress-plugin-k63):
> 
> 1. Install NodeJS, if not already installed
> 2. Navigate to the directory with your `.wpress` file
> 3. `npx wpress-extract yourfile.wpress`
> 4. Confirm the question asked

hero
