### ISSUE TITLE
Runtime error on mac

### ISSUE THREAD

**Issue by praad** [fifthsegment/Wpress-Extractor#16]
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x6f98e254ea9 pc=0x1df19]

runtime stack:
runtime.throw(0x13e800, 0x2a)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.(*gcWork).put(0xc82001c720, 0xc820494060)
	/usr/local/go/src/runtime/mgcwork.go:87 +0x49
runtime.greyobject(0xc820494060, 0x0, 0x0, 0xc81ffdb5fc, 0x0, 0x3c0500, 0xc82001c720)
	/usr/local/go/src/runtime/mgcmark.go:1015 +0x2f1
runtime.shade(0xc820494060)
	/usr/local/go/src/runtime/mgcmark.go:953 +0x9a
runtime.gcmarkwb_m(0xc8200001d8, 0xc820494060)
	/usr/local/go/src/runtime/mbarrier.go:91 +0xc1
runtime.writebarrierptr_nostore1.func1()
	/usr/local/go/src/runtime/mbarrier.go:117 +0x134
runtime.systemstack(0xc82003ddd8)
	/usr/local/go/src/runtime/asm_amd64.s:278 +0xab
runtime.writebarrierptr_nostore1(0xc8200001d8, 0xc820494060)
	/usr/local/go/src/runtime/mbarrier.go:118 +0x71
runtime.writebarrierptr_nostore(0xc8200001d8, 0xc820494060)
	/usr/local/go/src/runtime/mbarrier.go:150 +0x47
runtime.newstack()
	/usr/local/go/src/runtime/stack1.go:760 +0x8d9
runtime.morestack()
	/usr/local/go/src/runtime/asm_amd64.s:330 +0x7f

goroutine 1 [stack growth]:
bytes.makeCutsetFunc.func1(0x0, 0x1)
	/usr/local/go/src/bytes/bytes.go:572 fp=0xc820041b18 sp=0xc820041b10
bytes.lastIndexFunc(0xc8204bc119, 0x1000, 0x1000, 0xc820494060, 0xc8204bc100, 0x1000)
	/usr/local/go/src/bytes/bytes.go:564 +0xb3 fp=0xc820041b68 sp=0xc820041b18
bytes.TrimRightFunc(0xc8204bc119, 0x1000, 0x1000, 0xc820494060, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/bytes.go:487 +0x5f fp=0xc820041bc0 sp=0xc820041b68
bytes.TrimFunc(0xc8204bc119, 0x1000, 0x1000, 0xc820494060, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/bytes.go:500 +0x95 fp=0xc820041c18 sp=0xc820041bc0
bytes.Trim(0xc8204bc119, 0x1000, 0x1000, 0x117eb8, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/bytes.go:585 +0x68 fp=0xc820041c58 sp=0xc820041c18
github.com/yani-/wpress.Reader.Extract(0x7ffeefbffc8b, 0xb, 0xc82002e028, 0x8a, 0x0, 0x0, 0x0)
	/Users/abdullahirfan/go/src/github.com/yani-/wpress/reader.go:102 +0x3fb fp=0xc820041e60 sp=0xc820041c58
main.main()
	/Users/abdullahirfan/godev/wpress_extractor.go:16 +0x193 fp=0xc820041f50 sp=0xc820041e60
runtime.main()
	/usr/local/go/src/runtime/proc.go:111 +0x2b0 fp=0xc820041fa0 sp=0xc820041f50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc820041fa8 sp=0xc820041fa0

**Comment by AlistairThom** [comment]
Similar issue here...

fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x3174111aaeb7 pc=0x1e15a]

runtime stack:
runtime.throw(0x13e800, 0x2a)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.(*gcWork).dispose(0xc82001c720)
	/usr/local/go/src/runtime/mgcwork.go:164 +0x2a
runtime.gc.func2.1(0xc82001b500)
	/usr/local/go/src/runtime/mgc.go:1032 +0x30
runtime.runSafePointFn()
	/usr/local/go/src/runtime/proc1.go:837 +0x80
runtime.systemstack(0xc82001b500)
	/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc1.go:668

goroutine 1 [syscall]:
syscall.Syscall(0x4, 0x4, 0xc8204b1800, 0x200, 0x30adf, 0xc820000180, 0x200000003)
	/usr/local/go/src/syscall/asm_darwin_amd64.s:16 +0x5 fp=0xc820041ae8 sp=0xc820041ae0
syscall.write(0x4, 0xc8204b1800, 0x200, 0x200, 0x3, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_darwin_amd64.go:1360 +0x5f fp=0xc820041b28 sp=0xc820041ae8
syscall.Write(0x4, 0xc8204b1800, 0x200, 0x200, 0xc8204b1800, 0x0, 0x0)
	/usr/local/go/src/syscall/syscall_unix.go:176 +0x4d fp=0xc820041b68 sp=0xc820041b28
os.(*File).write(0xc82002e1a8, 0xc8204b1800, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:232 +0xd0 fp=0xc820041c00 sp=0xc820041b68
os.(*File).Write(0xc82002e1a8, 0xc8204b1800, 0x200, 0x200, 0x200, 0x0, 0x0)
	/usr/local/go/src/os/file.go:139 +0x8a fp=0xc820041c58 sp=0xc820041c00
github.com/yani-/wpress.Reader.Extract(0x7ffeefbffc5f, 0x6f, 0xc82002e028, 0x2f, 0x0, 0x0, 0x0)
	/Users/abdullahirfan/go/src/github.com/yani-/wpress/reader.go:136 +0x8d3 fp=0xc820041e60 sp=0xc820041c58
main.main()
	/Users/abdullahirfan/godev/wpress_extractor.go:16 +0x193 fp=0xc820041f50 sp=0xc820041e60
runtime.main()
	/usr/local/go/src/runtime/proc.go:111 +0x2b0 fp=0xc820041fa0 sp=0xc820041f50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc820041fa8 sp=0xc820041fa0


Thanks!

**Comment by metju90** [comment]
Same issue over here...

**Comment by carnevlu** [comment]
Hello,
I had the same issues but after recompile the source code everything was fine. 

## The solution step-by-step:
0. Clone this project where you wish, in my case `git cone https://github.com/fifthsegment/Wpress-Extractor.git ~/Desktop/Wpress-Extractor`
1. Open a terminal and go to the source code of this project `cd ~/Desktop/Wpress-Extractor`
2. Compile it `go build`
3. Now you will find a fresh new `Wpress-Extractor` binary,  
4. run on it `chmod +x Wpress-Extracto' to make it executable
5. move it where you wish and work with it

## Troubles
### Compiling error: no package found
In case of error `wpress-extractor.go:5:2: cannot find package "github.com/yani-/wpress" in any of:` please clone the dependencies in one of the folder listed in the error, in my case `git clone https://github.com/yani-/wpress.git ~/go/src/github.com/yani-/wpress` and start again from point 2.

### No `go` compiler
In this case be sure to have installed http://brew.sh/ on your macOS, and run in a terminal `brew install go`. Start again from point 2.

**Comment by cappadona** [comment]
Thanks @carnevlu. Minor tweak for me to address the package not found error. I set `GOPATH` and `GOROOT` and added them to my PATH:

```
export GOROOT=/usr/local/opt/go/libexec
export GOPATH=$HOME/.go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
```

After that, I was able to add the dependency via go:

```
❯ go get github.com/yani-/wpress
```

**Comment by goranefbl** [comment]
I suppose it has something to do with osX version as it was working before I've updated it, but @carnevlu solution did the job.

**Comment by jnaklaas** [comment]
> Hello,
> I had the same issues but after recompile the source code everything was fine.

There's an extra step I had to do in order to recompile after installing go with homebrew:

```
$ brew install go
$ go mod init wpress_extractor
$ go get github.com/yani-/wpress
$ go build
```
